# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_comm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'agent_comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61gent_comm.proto\x12\tagentcomm\"\x8d\x02\n\x0c\x41gentMessage\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x14\n\x0crecipient_id\x18\x02 \x01(\t\x12\x39\n\x0cmessage_type\x18\x03 \x01(\x0e\x32#.agentcomm.AgentMessage.MessageType\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x16\n\x0e\x63orrelation_id\x18\x06 \x01(\t\"]\n\x0bMessageType\x12\n\n\x06\x44IRECT\x10\x00\x12\r\n\tBROADCAST\x10\x01\x12\t\n\x05\x45VENT\x10\x02\x12\x0b\n\x07REQUEST\x10\x03\x12\x0c\n\x08RESPONSE\x10\x04\x12\r\n\tHEARTBEAT\x10\x05\">\n\x14RegisterAgentRequest\x12\x12\n\nagent_name\x18\x01 \x01(\t\x12\x12\n\nagent_type\x18\x02 \x01(\t\"I\n\x15RegisterAgentResponse\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2S\n\tAgentComm\x12\x46\n\x0eStreamMessages\x12\x17.agentcomm.AgentMessage\x1a\x17.agentcomm.AgentMessage(\x01\x30\x01\x32\x63\n\rAgentRegistry\x12R\n\rRegisterAgent\x12\x1f.agentcomm.RegisterAgentRequest\x1a .agentcomm.RegisterAgentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTMESSAGE']._serialized_start=32
  _globals['_AGENTMESSAGE']._serialized_end=301
  _globals['_AGENTMESSAGE_MESSAGETYPE']._serialized_start=208
  _globals['_AGENTMESSAGE_MESSAGETYPE']._serialized_end=301
  _globals['_REGISTERAGENTREQUEST']._serialized_start=303
  _globals['_REGISTERAGENTREQUEST']._serialized_end=365
  _globals['_REGISTERAGENTRESPONSE']._serialized_start=367
  _globals['_REGISTERAGENTRESPONSE']._serialized_end=440
  _globals['_AGENTCOMM']._serialized_start=442
  _globals['_AGENTCOMM']._serialized_end=525
  _globals['_AGENTREGISTRY']._serialized_start=527
  _globals['_AGENTREGISTRY']._serialized_end=626
# @@protoc_insertion_point(module_scope)
